name: Code Check
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint, ʦ TypeScript, and 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: 🔬 Lint
        run: yarn lint:strict

      - name: 🔎 Type check
        run: yarn typecheck

      - name: 💅 Prettier write
        run: yarn format:write

      - name: 💅 Prettier check
        run: yarn format:check
